server:
  port: ${PORT:8080}
  servlet:
    context-path: /transparency-portal
    session:
      persistent: false
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: transparency-portal
  profiles: 
      active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

jwt:
  secret: wihfbdfibgdfi374543#%$%BIFD*^%$bhsdsdfsdg36528bsDVDA
  expiration: 3600000